(define (make-node datum children)
  (cons datum children))

(define (make-leaf datum)
  (cons datum '()))

(define (datum node)
  (car node))

(define (children node)
  (cdr node))

(define (add-child node child)
  (make-node (datum node) (append (children node) (list child))))

(define (parse exp)
  (cond ((null? exp) '())
	((number? (car exp))
	 (if (null? (cdr exp))
	     (make-node (car exp) '())
	     (make-node (cadr exp) (list (make-node (car exp) '()) (parse (cddr exp))))))
	(else exp)))

(define (parse exp)
  (define (precedes? a b)
    (and (or (equal? a '*)
	     (equal? a '/))
	 (or (equal? b '+)
	     (equal? b '-))))
  (define (sub prev exp)
    (cond ((null? exp) prev)
	  ((number? (car exp))
	   (if (null? (cdr exp))
	       (add-child prev (make-leaf (car exp)))
	       (let ((op (cadr exp)))
		 (if (precedes? (datum prev) op)
		     (make-node op (list (add-child prev (make-leaf (car exp))) (parse (cddr exp))))
		     (add-child prev (parse exp))))))
	  (else exp)))

  (cond ((null? exp) '())
	((number? (car exp))
	 (if (null? (cdr exp))
	     (make-node (car exp) '())
	     (sub (make-node (cadr exp)
			     (list (make-leaf (car exp))))
		  (cddr exp))))
	(else exp)))
  
(parse '(4 + 3))	 
(parse '(4 + 3 * 7 - 5 / (3 + 4) + 6))
